# Generated by Django 4.0.6 on 2022-08-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_product_memory_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
